<?php

/**
 * Do not edit this file. Edit the config files found in the config/ dir instead.
 * This file is required in the root directory so WordPress can find it.
 * WP is hardcoded to look in its own directory or one directory up for wp-config.php.
 */

define('DS', DIRECTORY_SEPARATOR);
define('APP_ROOT', dirname(__DIR__));
define('WEB_ROOT', 'public');
define('WP_CORE_DIRNAME', 'wp');
define('WP_CONTENT_DIRNAME', 'app');
define('WP_CONTENT_DIR', realpath(APP_ROOT . DS . WEB_ROOT . DS . WP_CONTENT_DIRNAME));

require_once dirname(__DIR__) . '/vendor/autoload.php';
require_once dirname(__DIR__) . '/bootstrap/app.php';
require_once dirname(__DIR__) . '/bootstrap/system.php';
require_once ABSPATH . 'wp-settings.php';
